version: '3.4'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  mysqldata:

services:
  #DataBase Service
  database:
    #Pull the latest mysql image
    image: mysql:8.0.27
    #Map port 3306 on the mysql container to port 3306 in the host
    ports:
      - "3306:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - mysqldata:/data/db
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 67db7e34-7788-4be3-b24c-ff29afbccb9a
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: v7UzHhcCvJJONmWk
      MYSQL_DATABASE: newsportal
  #Api  Service
  api:
    build:
      context: .
      #Use the DockerFile in that Directory
      dockerfile: Dockerfile
    #This Service Depends on the database service specifed above
    depends_on: 
      - database
    #Map port 8888 in the docker container to port 80 in the Api
    ports:
      - "80:5000"
    restart: always
    #Specify Environment Variables for the Api Service
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development